In [2]:
import pandas as pd

In [10]:
#how i can import the file in to the jupyter
movies = pd.read_csv(r"C:\Data_Science\movie.csv\movie.csv")
movies.head(27278)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy
27275,131258,The Pirates (2014),Adventure
27276,131260,Rentun Ruusu (2001),(no genres listed)
27277,131262,Innocence (2014),Adventure|Fantasy|Horror

In [11]:
movies.shape[0]

27278

In [10]:
#i want  to import the Tags
tags= pd.read_csv(r"C:\Data_Science\tag.csv\tag.csv")
tags.head(20)

    userId  movieId                tag            timestamp
0       18     4141        Mark Waters  2009-04-24 18:19:40
1       65      208          dark hero  2013-05-10 01:41:18
2       65      353          dark hero  2013-05-10 01:41:19
3       65      521      noir thriller  2013-05-10 01:39:43
4       65      592          dark hero  2013-05-10 01:41:18
5       65      668          bollywood  2013-05-10 01:37:56
6       65      898   screwball comedy  2013-05-10 01:42:40
7       65     1248      noir thriller  2013-05-10 01:39:43
8       65     1391               mars  2013-05-10 01:40:55
9       65     1617           neo-noir  2013-05-10 01:43:37
10      65     1694              jesus  2013-05-10 01:38:45
11      65     1783      noir thriller  2013-05-10 01:39:43
12      65     2022              jesus  2013-05-10 01:38:45
13      65     2193             dragon  2013-05-10 02:01:54
14      65     2353  conspiracy theory  2013-05-10 02:01:06
15      65     2662               mars  2013-05-10 01:40:55
16      65     2726      noir thriller  2013-05-10 01:39:43
17      65     2840              jesus  2013-05-10 01:38:45
18      65     3052              jesus  2013-05-10 01:38:46
19      65     5135          bollywood  2013-05-10 01:37:56

In [4]:
#I  wwant to import the rating dude
ratings=pd.read_csv(r"C:\Data_Science\rating.csv\rating.csv")
print(ratings)

          userId  movieId  rating            timestamp
0              1        2     3.5  2005-04-02 23:53:47
1              1       29     3.5  2005-04-02 23:31:16
2              1       32     3.5  2005-04-02 23:33:39
3              1       47     3.5  2005-04-02 23:32:07
4              1       50     3.5  2005-04-02 23:29:40
...          ...      ...     ...                  ...
20000258  138493    68954     4.5  2009-11-13 15:42:00
20000259  138493    69526     4.5  2009-12-03 18:31:48
20000260  138493    69644     3.0  2009-12-07 18:10:57
20000261  138493    70286     5.0  2009-11-13 15:42:24
20000262  138493    71619     2.5  2009-10-17 20:25:36

[20000263 rows x 4 columns]