In [2]:
import pandas as pd

In [5]:
#how i can import the file in to the jupyter
movies = pd.read_csv(r"C:\Data_Science\movie.csv\movie.csv")
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy
27275,131258,The Pirates (2014),Adventure
27276,131260,Rentun Ruusu (2001),(no genres listed)
27277,131262,Innocence (2014),Adventure|Fantasy|Horror

In [11]:
movies.shape[0]

27278

In [16]:
#i want  to import the Tags
tags= pd.read_csv(r"C:\Data_Science\tag.csv\tag.csv")

tags

        userId  movieId            tag            timestamp
0           18     4141    Mark Waters  2009-04-24 18:19:40
1           65      208      dark hero  2013-05-10 01:41:18
2           65      353      dark hero  2013-05-10 01:41:19
3           65      521  noir thriller  2013-05-10 01:39:43
4           65      592      dark hero  2013-05-10 01:41:18
...        ...      ...            ...                  ...
465559  138446    55999        dragged  2013-01-23 23:29:32
465560  138446    55999  Jason Bateman  2013-01-23 23:29:38
465561  138446    55999         quirky  2013-01-23 23:29:38
465562  138446    55999            sad  2013-01-23 23:29:32
465563  138472      923  rise to power  2007-11-02 21:12:47

[465564 rows x 4 columns]

In [10]:
#I  wwant to import the rating dude
ratings=pd.read_csv(r"C:\Data_Science\rating.csv\rating.csv")
print(ratings)

          userId  movieId  rating            timestamp
0              1        2     3.5  2005-04-02 23:53:47
1              1       29     3.5  2005-04-02 23:31:16
2              1       32     3.5  2005-04-02 23:33:39
3              1       47     3.5  2005-04-02 23:32:07
4              1       50     3.5  2005-04-02 23:29:40
...          ...      ...     ...                  ...
20000258  138493    68954     4.5  2009-11-13 15:42:00
20000259  138493    69526     4.5  2009-12-03 18:31:48
20000260  138493    69644     3.0  2009-12-07 18:10:57
20000261  138493    70286     5.0  2009-11-13 15:42:24
20000262  138493    71619     2.5  2009-10-17 20:25:36

[20000263 rows x 4 columns]

In [7]:
#i Just want to know how much rows in  the movie dataset
movies.shape[0]

27278

In [11]:
#I want to know how much rows in the rating dataset
ratings.shape[0]

20000263

In [17]:
# i want to know the rows in the tag dataset
tags.shape[0]

465564

In [20]:
#  i want to know which dataset contains the highest columns
#highestcol=[movies.shape[1],ratings.shape[1],tags.shape[1]].max() #This is the wrong way
highestcol=max([movies.shape[1],ratings.shape[1],tags.shape[1]])
highestcol

4

In [21]:
#By using this one u can get the both the highest column and also the highest column name
datasets = {
    "movies": movies.shape[1],
    "ratings": ratings.shape[1],
    "tags": tags.shape[1]
}

name = max(datasets, key=datasets.get)

print("Dataset Name =", name)
print("Column Count =", datasets[name])

Dataset Name = ratings
Column Count = 4

In [27]:
#movie titile data we can see
movies['title']

0                          Toy Story (1995)
1                            Jumanji (1995)
2                   Grumpier Old Men (1995)
3                  Waiting to Exhale (1995)
4        Father of the Bride Part II (1995)
                        ...
27273          Kein Bund für's Leben (2007)
27274         Feuer, Eis & Dosenbier (2002)
27275                    The Pirates (2014)
27276                   Rentun Ruusu (2001)
27277                      Innocence (2014)
Name: title, Length: 27278, dtype: object

In [28]:
movies['genres']

0        Adventure|Animation|Children|Comedy|Fantasy
1                         Adventure|Children|Fantasy
2                                     Comedy|Romance
3                               Comedy|Drama|Romance
4                                             Comedy
                            ...
27273                                         Comedy
27274                                         Comedy
27275                                      Adventure
27276                             (no genres listed)
27277                       Adventure|Fantasy|Horror
Name: genres, Length: 27278, dtype: object

In [31]:
print(ratings.max())

userId                    138493
movieId                   131262
rating                       5.0
timestamp    2015-03-31 06:40:02
dtype: object

In [32]:
print(ratings.min())

userId                         1
movieId                        1
rating                       0.5
timestamp    1995-01-09 11:46:44
dtype: object

In [ ]:
print(ratings.mean())

In [ ]:
#I want to know the unique ratingd means not repeated
ratings['rating'].unique()

In [ ]:
#most movieid range
import seaborn as sns

In [ ]:
sns.boxplot(x=movies['movieId'])